spring.application.name=backend

# JPA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=604800000

# OAuth2
oauth2.redirect-uri=${OAUTH2_REDIRECT_URI:http://localhost:3000/oauth2/callback}
