package com.oshifes.domain.event.application;

import com.oshifes.domain.event.api.dto.EventResponse;
import com.oshifes.domain.event.api.dto.EventSearchCondition;
import com.oshifes.domain.event.dao.EventRepository;
import com.oshifes.domain.event.entity.Event;
import com.oshifes.global.error.CustomException;
import com.oshifes.global.error.ErrorCode;
import com.oshifes.global.config.JpaAuditingConfig;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.jdbc.Sql;

import java.time.LocalDate;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
@Import(JpaAuditingConfig.class)
@Sql(statements = {
        "drop table if exists event",
        "create table event (id bigint generated by default as identity primary key, title varchar(255) not null, description text, category varchar(255) not null, country varchar(255) not null, start_date date, end_date date, venue_name varchar(255), address varchar(255), location varchar(255), image_url varchar(255), source_url varchar(255), external_id varchar(255), source_type varchar(255) not null, is_auto_translated boolean not null, extra varchar(255), deleted_at timestamp, created_at timestamp not null, updated_at timestamp not null)"
})
class EventServiceFilterIntegrationTest {

    @Autowired
    private EventRepository eventRepository;

    @Test
    void getEvents_countryFilter_returnsOnlyMatchingCountry() {
        Event krEvent = saveEvent("KR 행사", "KR", "concert",
                LocalDate.of(2026, 5, 1), LocalDate.of(2026, 5, 31));
        saveEvent("JP 행사", "JP", "concert",
                LocalDate.of(2026, 5, 1), LocalDate.of(2026, 5, 31));
        EventService eventService = new EventService(eventRepository);

        Page<EventResponse> result = eventService.getEvents(
                new EventSearchCondition("KR", null, null, null),
                PageRequest.of(0, 20)
        );

        assertThat(result.getContent())
                .extracting(EventResponse::getId)
                .containsExactly(krEvent.getId());
    }

    @Test
    void getEvents_categoryFilter_returnsOnlyMatchingCategory() {
        Event concertEvent = saveEvent("콘서트", "KR", "concert",
                LocalDate.of(2026, 5, 1), LocalDate.of(2026, 5, 31));
        saveEvent("페스티벌", "KR", "festival",
                LocalDate.of(2026, 5, 1), LocalDate.of(2026, 5, 31));
        EventService eventService = new EventService(eventRepository);

        Page<EventResponse> result = eventService.getEvents(
                new EventSearchCondition(null, "concert", null, null),
                PageRequest.of(0, 20)
        );

        assertThat(result.getContent())
                .extracting(EventResponse::getId)
                .containsExactly(concertEvent.getId());
    }

    @Test
    void getEvents_monthFilter_returnsEventsOverlappingMonth() {
        Event mayEvent = saveEvent("5월 행사", "KR", "concert",
                LocalDate.of(2026, 4, 25), LocalDate.of(2026, 5, 5));
        Event singleDayMayEvent = saveEvent("5월 단일 행사", "KR", "concert",
                LocalDate.of(2026, 5, 10), null);
        saveEvent("6월 행사", "KR", "concert",
                LocalDate.of(2026, 6, 1), LocalDate.of(2026, 6, 30));
        EventService eventService = new EventService(eventRepository);

        Page<EventResponse> result = eventService.getEvents(
                new EventSearchCondition(null, null, "2026-05", null),
                PageRequest.of(0, 20)
        );

        assertThat(result.getContent())
                .extracting(EventResponse::getId)
                .containsExactlyInAnyOrder(mayEvent.getId(), singleDayMayEvent.getId());
    }

    @Test
    void getEvents_invalidMonth_throwsInvalidInputException() {
        EventService eventService = new EventService(eventRepository);

        assertThatThrownBy(() -> eventService.getEvents(
                new EventSearchCondition(null, null, "2026/05", null),
                PageRequest.of(0, 20)
        ))
                .isInstanceOf(CustomException.class)
                .extracting(e -> ((CustomException) e).getErrorCode())
                .isEqualTo(ErrorCode.INVALID_INPUT_VALUE);
    }

    private Event saveEvent(String title, String country, String category,
                            LocalDate startDate, LocalDate endDate) {
        return eventRepository.save(Event.builder()
                .title(title)
                .description("설명")
                .category(category)
                .country(country)
                .startDate(startDate)
                .endDate(endDate)
                .sourceType("manual")
                .build());
    }
}
