CREATE TABLE IF NOT EXISTS user_character_birthday (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    character_id bigint NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT fk_user_character_birthday_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_character_birthday_character
        FOREIGN KEY (character_id) REFERENCES character (id),
    CONSTRAINT uk_user_character_birthday_user_character
        UNIQUE (user_id, character_id)
);

CREATE INDEX IF NOT EXISTS ix_user_character_birthday_user_id
    ON user_character_birthday (user_id);

CREATE INDEX IF NOT EXISTS ix_user_character_birthday_character_id
    ON user_character_birthday (character_id);
