package com.oshifes.domain.ip.dao;

import com.oshifes.domain.ip.entity.Character;
import com.oshifes.domain.ip.entity.IpTitle;
import com.oshifes.global.config.JpaAuditingConfig;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.jdbc.Sql;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
@Import(JpaAuditingConfig.class)
@Sql(statements = {
        "drop table if exists character",
        "drop table if exists ip_title",
        "create domain if not exists jsonb as varchar(255)",
        "create table ip_title (id bigint generated by default as identity primary key, name_ko varchar(255) not null, name_ja varchar(255), name_en varchar(255), category varchar(255) not null, thumbnail_url varchar(255), source_type varchar(255), external_id varchar(255), source_url varchar(255), is_auto_translated boolean not null, extra jsonb, created_at timestamp not null, updated_at timestamp not null)",
        "create table character (id bigint generated by default as identity primary key, ip_title_id bigint not null, name_ko varchar(255) not null, name_ja varchar(255), birthday_month integer, birthday_day integer, image_url varchar(255), source_type varchar(255), external_id varchar(255), source_url varchar(255), is_auto_translated boolean not null, extra jsonb, created_at timestamp not null, updated_at timestamp not null)"
})
class CharacterRepositoryTest {

    @Autowired
    private CharacterRepository characterRepository;

    @Autowired
    private IpTitleRepository ipTitleRepository;

    @Test
    void searchBirthdays_excludesCharactersWithoutCompleteBirthday() {
        saveCharacter("생일 있음", 11, 11);
        saveCharacter("월 없음", null, 11);
        saveCharacter("일 없음", 11, null);

        Page<Character> result = characterRepository.searchBirthdays(null, null, PageRequest.of(0, 20));

        assertThat(result.getContent())
                .extracting(Character::getNameKo)
                .containsExactly("생일 있음");
    }

    @Test
    void searchByKeyword_excludesCharactersWithoutCompleteBirthday() {
        saveCharacter("나카노 아즈사", 11, 11);
        saveCharacter("나카노 미등록", null, null);

        List<Character> result = characterRepository.searchByKeyword("나카노");

        assertThat(result)
                .extracting(Character::getNameKo)
                .containsExactly("나카노 아즈사");
    }

    @Test
    void findByBirthdayMonth_excludesCharactersWithoutBirthdayDay() {
        saveCharacter("생일 있음", 11, 11);
        saveCharacter("일 없음", 11, null);

        List<Character> result = characterRepository.findByBirthdayMonth(11);

        assertThat(result)
                .extracting(Character::getNameKo)
                .containsExactly("생일 있음");
    }

    private Character saveCharacter(String nameKo, Integer month, Integer day) {
        IpTitle ipTitle = ipTitleRepository.save(IpTitle.builder()
                .nameKo("케이온!")
                .category("anime")
                .build());
        return characterRepository.save(Character.builder()
                .ipTitle(ipTitle)
                .nameKo(nameKo)
                .birthdayMonth(month)
                .birthdayDay(day)
                .build());
    }
}
