package com.oshifes.domain.ip.dao;

import com.oshifes.domain.ip.entity.Character;
import com.oshifes.domain.ip.entity.IpTitle;
import com.oshifes.domain.ip.entity.UserCharacterBirthday;
import com.oshifes.domain.user.dao.UserRepository;
import com.oshifes.domain.user.entity.User;
import com.oshifes.domain.user.entity.UserRole;
import com.oshifes.global.config.JpaAuditingConfig;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.jdbc.Sql;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
@Import(JpaAuditingConfig.class)
@Sql(statements = {
        "drop table if exists user_character_birthday",
        "drop table if exists character",
        "drop table if exists ip_title",
        "drop table if exists users",
        "create domain if not exists jsonb as varchar(255)",
        "create table users (id bigint generated by default as identity primary key, provider varchar(255) not null, provider_id varchar(255) not null, nickname varchar(255) not null, profile_image_url varchar(255), role varchar(255) not null, created_at timestamp not null, updated_at timestamp not null)",
        "create table ip_title (id bigint generated by default as identity primary key, name_ko varchar(255) not null, name_ja varchar(255), name_en varchar(255), category varchar(255) not null, thumbnail_url varchar(255), source_type varchar(255), external_id varchar(255), source_url varchar(255), is_auto_translated boolean not null, extra jsonb, created_at timestamp not null, updated_at timestamp not null)",
        "create table character (id bigint generated by default as identity primary key, ip_title_id bigint not null, name_ko varchar(255) not null, name_ja varchar(255), birthday_month integer, birthday_day integer, image_url varchar(255), source_type varchar(255), external_id varchar(255), source_url varchar(255), is_auto_translated boolean not null, extra jsonb, created_at timestamp not null, updated_at timestamp not null)",
        "create table user_character_birthday (id bigint generated by default as identity primary key, user_id bigint not null, character_id bigint not null, created_at timestamp not null, updated_at timestamp not null)"
})
class UserCharacterBirthdayRepositoryTest {

    @Autowired
    private UserCharacterBirthdayRepository userCharacterBirthdayRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private CharacterRepository characterRepository;

    @Autowired
    private IpTitleRepository ipTitleRepository;

    @Test
    void searchBirthdays_excludesInvalidBirthdayAndKeepsTotalAccurate() {
        User user = saveUser();
        saveUserCharacterBirthday(user, "생일 있음", 11, 11);
        saveUserCharacterBirthday(user, "잘못된 생일", 2, 31);

        Page<UserCharacterBirthday> result =
                userCharacterBirthdayRepository.searchBirthdays(user.getId(), null, null, PageRequest.of(0, 20));

        assertThat(result.getContent())
                .extracting(userCharacterBirthday -> userCharacterBirthday.getCharacter().getNameKo())
                .containsExactly("생일 있음");
        assertThat(result.getTotalElements()).isEqualTo(1);
    }

    @Test
    void findUpcomingBirthdaysByUserId_ordersFromTodayAndLimitsInRepository() {
        User user = saveUser();
        saveUserCharacterBirthday(user, "지난 생일", 5, 1);
        saveUserCharacterBirthday(user, "오늘 생일", 5, 6);
        saveUserCharacterBirthday(user, "올해 생일", 5, 10);

        List<UserCharacterBirthday> result =
                userCharacterBirthdayRepository.findUpcomingBirthdaysByUserId(user.getId(), 5, 6, PageRequest.of(0, 2));

        assertThat(result)
                .extracting(userCharacterBirthday -> userCharacterBirthday.getCharacter().getNameKo())
                .containsExactly("오늘 생일", "올해 생일");
    }

    @Test
    void deleteByUserIdAndCharacterId_deletesWithoutLoadingCollection() {
        User user = saveUser();
        Character character = saveUserCharacterBirthday(user, "나카노 아즈사", 11, 11).getCharacter();

        long deleted = userCharacterBirthdayRepository.deleteByUserIdAndCharacterId(user.getId(), character.getId());

        assertThat(deleted).isEqualTo(1);
        assertThat(userCharacterBirthdayRepository.findByUserIdAndCharacterId(user.getId(), character.getId()))
                .isEmpty();
    }

    private UserCharacterBirthday saveUserCharacterBirthday(User user, String nameKo, Integer month, Integer day) {
        Character character = saveCharacter(nameKo, month, day);
        return userCharacterBirthdayRepository.save(UserCharacterBirthday.builder()
                .user(user)
                .character(character)
                .build());
    }

    private Character saveCharacter(String nameKo, Integer month, Integer day) {
        IpTitle ipTitle = ipTitleRepository.save(IpTitle.builder()
                .nameKo("케이온!")
                .category("anime")
                .build());
        return characterRepository.save(Character.builder()
                .ipTitle(ipTitle)
                .nameKo(nameKo)
                .birthdayMonth(month)
                .birthdayDay(day)
                .build());
    }

    private User saveUser() {
        return userRepository.save(User.createNewUser("google", "google-1", "테스트", null, UserRole.USER));
    }
}
